{{- if .Values.prehook.identity.enabled }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.name }}-hook
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "hook.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-4"
spec:
  azureIdentity: {{ .Values.name }}-hook
  selector: {{ .Values.name }}
{{ end }}