{{- if and .Values.prehook.hooksecret.enabled .Values.prehook.hooksecret.data -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{.Values.name}}-hook-secret
  labels: {{- include "common.labels" . | nindent 4}}
  annotations:
    {{- include "hook.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-6"
spec:
  encryptedData:
    {{- range $k, $v := .Values.prehook.hooksecret.data }}
    {{- range $kk, $vv := $v }}
    {{ $kk }}: {{ $vv }}
    {{- end }}
    {{- end }}
{{- end}}