{{- if .Values.identity.enabled }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.name }}-binding
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  azureIdentity: {{ .Values.name | quote }}
  selector: {{ .Values.name | quote }}
{{ end }}