{{- if and .Values.secret.enabled .Values.secret.data -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{.Values.name}}-secret
  labels: {{- include "common.labels" . | nindent 4}}
spec:
  encryptedData:
    {{- range $k, $v := .Values.secret.data }}
    {{- range $kk, $vv := $v }}
    {{ $kk }}: {{ $vv }}
    {{- end }}
    {{- end }}
{{- end }}
