{{- if or .Values.deployment.enabled .Values.cronjob.enabled }} 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{- end }}